### ISSUE TITLE
Attachments don't download

### ISSUE THREAD

**Issue by ddolcimascolo** [jmapio/jmap-perl#10]
It's because of the BINARY fetch command the proxy is sending.
I don't understand exactly why as I'm no IMAP expert, but using BODY instead works fine.

**Comment by brong** [comment]
Resolved in 52a31448c40324290a7415c710fe763f7f5cdf53 - thanks for reporting

**Comment by ddolcimascolo** [comment]
Hey Bron, your patch works on GMail, thanks a lot for the quick implementation !

FYI, here's their capabilities:
`1 * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE       ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS APPENDLIMIT=35882577`
