### ISSUE TITLE
Header decoding charset problem

### ISSUE THREAD

**Issue by thomascube** [jmapio/jmap-perl#21]
When accessing messages with UTF-8 quoted-printable encoded headers, the values exposed in the JSON response by the JMAP proxy contain wrongly encoded unicode characters.

The following subject header in the original IMAP message

```
Subject: =?UTF-8?Q?Bern:=20Vari=C3=A9t=C3=A9,=20Juliette=20&=20Meeressause?=
```

results in a response

```
[
    "messages",
    {
        "accountId": "xxxxx",
        "list": [
            {
                "headers": {
                    "Subject": "Bern: VariÃ©tÃ©, Juliette & Meeressause",
                    ...
                },
                ...
                "subject": "Bern: VariÃ©tÃ©, Juliette & Meeressause",
                ...
            }
        ]
    },
    "#1"
]
```

It appears that the decoded header value is treated as iso-8859-1 encoded and is then converted to utf-8 resulting in a double encoding.

**Comment by thomascube** [comment]
Looking into the sqlite3 database, the values seem to be stored correctly as utf-8 strings.

```
sqlite> select msgsubject from jmessages where msgid='m717d45f12';
Bern: Variété, Juliette & Meeressause
```

**Comment by brong** [comment]
This is fixed by

commit 9c83cee88a9dc038f6b8b15e7421b0f1d57bb667
Author: Bron Gondwana brong@fastmail.fm
Date:   Fri May 27 00:19:55 2016 -0400

```
don't double-encode utf8
```

...

The bug was in the server.pl.
