### ISSUE TITLE
imap sync breaks when a folder is deleted at IMAP end

### ISSUE THREAD

**Issue by rjbs** [jmapio/jmap-perl#25]
If a mailbox is deleted at the remote (IMAP) end, IMAP syncing will fail in several ways, and no new syncs will occur.  Here's the report I had originally given via private email, here for easy future reference:

I noted this error:

  ERROR Not a HASH reference at /home/jmap/jmap-perl/JMAP/ImapDB.pm line 672.
     on c4de019e-1c5e-11e6-b873-f23c91556942:sync (dropping backend)

It's _one_ place where the problem can occur.  Here's that line, reformatted:

``` perl
  next if (
    $status->{$row->{imapname}}{uidvalidity} == $row->{uidvalidity}
    and $status->{$row->{imapname}}{highestmodseq}
    and $status->{$row->{imapname}}{highestmodseq} == $row->{highestmodseq}
  );
```

The undef being hash-dereferenced is `$status->{$row->{imapname}}`.  We got the status for every folder, but the status entry for a deleted folder is `\'no'` and not a hash ref.  `(\$string)->{...}` is fatal.

I started by just adding another "next"-ing condition, but this comes up elsewehere, too.  Many of the `imap_*` methods in JMAP::Sync::Common rely on being able EXAMINE folders that may have been deleted.

**Comment by brong** [comment]
This is not going to be easy to fix, but I have a plan around catching failures on get commands and doing a sync and then trying again.

**Comment by brong** [comment]
This is pretty much fixed by:

commit abe940071f188436cf006465f9282e6e719628a3
Author: Bron Gondwana brong@fastmail.fm
Date:   Thu May 26 21:37:52 2016 -0400

```
API: run syncs BEFORE any set command to pick up IMAP changes

This is still a small race condition, but it's tons better
```
