### ISSUE TITLE
Not performing unread flag changes

### ISSUE THREAD

**Issue by robn** [jmapio/jmap-perl#3]
This had some setup. I have four messages in a FastMail account. All were unread. Via JMAP, I can see that they were all unread. All good.

In FastMail, I read two of them. FastMail does the right thing and I can confirm it worked via IMAP:

```
. SELECT INBOX
* 4 EXISTS
* 0 RECENT
* FLAGS (\Answered \Flagged \Draft \Deleted \Seen $X-ME-Annot-2 $IsMailingList $IsNotification $HasAttachment $HasTD $IsTrusted $NotJunk $Forwarded $Junk $X-FM-Device-Push)
* OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $X-ME-Annot-2 $IsMailingList $IsNotification $HasAttachment $HasTD $IsTrusted $NotJunk $Forwarded $Junk $X-FM-Device-Push \*)] Ok
* OK [UNSEEN 3] Ok
* OK [UIDVALIDITY 1386137841] Ok
* OK [UIDNEXT 3129] Ok
* OK [HIGHESTMODSEQ 17365878007025304772] Ok
* OK [URLMECH INTERNAL] Ok
* OK [ANNOTATIONS 65536] Ok
. OK [READ-WRITE] Completed
. FETCH 1:* (FLAGS)
* 1 FETCH (FLAGS (\Seen $X-ME-Annot-2))
* 2 FETCH (FLAGS (\Seen $X-ME-Annot-2))
* 3 FETCH (FLAGS ($X-ME-Annot-2))
* 4 FETCH (FLAGS ($X-ME-Annot-2))
. OK Completed (0.000 sec)
```

The flag changes aren't reflected via the proxy, including in the client.

In the `getMailboxes` response:

```
            {
               "id" : "9",
               "mayAddItems" : true,
               "mayCreateChild" : true,
               "mayDelete" : false,
               "mayReadItems" : true,
               "mayRemoveItems" : true,
               "mayRename" : false,
               "mustBeOnlyMailbox" : true,
               "name" : "Inbox",
               "parentId" : null,
               "role" : "inbox",
               "sortOrder" : 1,
               "totalMessages" : 4,
               "totalThreads" : 4,
               "unreadMessages" : 4,
               "unreadThreads" : 4
            },
```

The individual messages all have `isUnread: true` as well (not showing here, its loooooong).

Further, changing the `isUnread` flag (by opening a message) doesn't do the right thing:

```
[
   [
      "setMessages",
      {
         "create" : {},
         "destroy" : [],
         "state" : "328",
         "update" : {
            "m76fdbd6d5" : {
               "isUnread" : false
            }
         }
      },
      "0"
   ],
   [
      "getMailboxes",
      {
         "ids" : [
            "9"
         ],
         "properties" : [
            "totalMessages",
            "unreadMessages",
            "totalThreads",
            "unreadThreads"
         ]
      },
      "1"
   ]
]
```

```
[
   [
      "messagesSet",
      {
         "accountId" : "9e2e4652-3191-11e5-847c-0026b9fac7aa",
         "created" : {},
         "destroyed" : [],
         "newState" : null,
         "notCreated" : {},
         "notDestroyed" : {},
         "notUpdated" : {},
         "oldState" : null,
         "updated" : [
            "m76fdbd6d5"
         ]
      },
      "0"
   ],
   [
      "mailboxes",
      {
         "accountId" : "9e2e4652-3191-11e5-847c-0026b9fac7aa",
         "list" : [
            {
               "id" : "9",
               "totalMessages" : 4,
               "totalThreads" : 4,
               "unreadMessages" : 4,
               "unreadThreads" : 4
            }
         ],
         "notFound" : null,
         "state" : "328"
      },
      "1"
   ]
]
```

So it claims the update has occurred, but that's not reflected in the `mailboxes` response, and there's no change on the backend IMAP server either.

**Comment by brong** [comment]
Damn - I guess I'd better debug it.  I'm sure this has been tested, so
your account probably got into some weird state....

**Comment by neilj** [comment]
There's also weirdness going on as described [here](https://github.com/jmapio/jmap-demo-webmail/issues/1) and totally bogus responses to setMessages [described here](https://github.com/jmapio/jmap-js/issues/3)…

**Comment by brong** [comment]
OK,

I'm luckily at a good point to drop everything again in next week and go full-time back on the JMAP proxy.  I'll investigate these things :)

Bron.

**Comment by cooperpellaton** [comment]
Has this issue persisted? Could this be coming from the way that the messages are being filtered in `getMessageListUpdates` wherein the state change is not reflected because it's hard to track differences in the dataset as it is transformed?

**Comment by brong** [comment]
There was a bug that got fixed here:

https://github.com/jmapio/jmap-perl/commit/af8871455e9c920092f902a76ef46343bdb53a8b

and it also got fixed to make moves much less horrible (disappear/appear) here:

https://github.com/jmapio/jmap-perl/commit/d78926e5a0f74953e69834f554006d6028988f20
